theme: jekyll-theme-minimal
title: [Meanings of Places,,,,,,,,, Space and Time]
description: [I study how people perceive the world from the perspective of geographic information science. Currently I am interested in place names and their implications.]
